### PR TITLE
feat: Add pyproject.toml

### PR DESCRIPTION
**Pull request by goyalyashpal**
Close: https://github.com/audreyfeldroy/cookiecutter-pypackage/issues/585

Please do test it as i am just following the documentations online and have no experience with these tools.

----
Existing files dealt with:
* setup.py
* requirements_dev.txt
* tox.ini
* pytest.ini
* setup.cfg

Refs: 
* `pdm import` (https://github.com/davisking/dlib/pull/2830)
* lucasrcezimbra https://github.com/lucasrcezimbra/cookiecutter-pypackage/commit/d63565c9c1e417f3d77e0e7909df096348d6dc0e 
  + arrays at last of project table: [here](https://github.com/lucasrcezimbra/cookiecutter-pypackage/commit/d63565c9c1e417f3d77e0e7909df096348d6dc0e#diff-99cadb42828eef8990700afeb15e9c1d8c83a933efc8b682f2af7cb3275773caR16)
  + project dev related things dealt separately: [here](https://github.com/lucasrcezimbra/cookiecutter-pypackage/commit/d63565c9c1e417f3d77e0e7909df096348d6dc0e#diff-99cadb42828eef8990700afeb15e9c1d8c83a933efc8b682f2af7cb3275773caR40)
  + tox testing: [here](https://github.com/lucasrcezimbra/cookiecutter-pypackage/commit/d63565c9c1e417f3d77e0e7909df096348d6dc0e#diff-99cadb42828eef8990700afeb15e9c1d8c83a933efc8b682f2af7cb3275773caR78-R106)

Documentations:
* pyproject
* setuptools
* tox
* pytest
* bump-my-version

### CODE REVIEW

**Comment by goyalyashpal** [comment]
oops, i think i have added it to root directory of the repo, rather than root of the `{{cookiecutter.project_slug}}` dir. 'will fix it soon.

**Comment by goyalyashpal** [comment]
@staticdev can u help a bit in reviewing? i can't quite figure out what the right things for tox.ini would be. the used existing one seems to be in outdated format.

**Comment by audreyfeldroy** [comment]
Thanks for the PR @goyalyashpal! 

When I try to generate a package using the defaults, I get an error. See https://gist.github.com/audreyfeldroy/64721ac7151c1f8401794d79f6be065b

**Comment by goyalyashpal** [comment]
hi @ audreyfeldroy 

sure, i will look into it. thanks for trying.

**Comment by pydanny** [comment]
This was absorbed in #716, you were given full attribution. Thank you so much for contributing!

**Comment by goyalyashpal** [comment]
😄 👍 🚀

**Pull request closed without merging**
