### PR TITLE
Introduces Black linter (disabled by default), closes #575

### LINKED ISSUE #575: Plans to use black? Are pull requests welcome?
Is there plan to use black https://github.com/psf/black ?
If so are pull requests integrating it welcome?

### PR DESCRIPTION
**Pull request by AndreMiras**
This is a first iteration with things kept simple. In the future I think we should do things like actually running both linters (flake and black) on the generated project via `tests/test_bake_project.py`.
Among other things I can also later provide a `make format` target that automatically fixes linter issues.
If things go as planned we can also add the `isort` linting option too

### CODE REVIEW

**Comment by hXtreme** [comment]
Just pinging here because there seems to be a problem with TravisCI. [Here](https://travis-ci.org/github/audreyr/cookiecutter-pypackage/builds/668491251) it says the build has passed but github says that the build is pending.

@AndreMiras you might wanna push an empty commit or force-push to trigger the CI again and hopefully fix this.

_(I really like black and would love to see this merged soon)_

**Comment by hrishikeshrt** [comment]
Any updates on this?

**Comment by AndreMiras** [comment]
I've updated the pull request fixing merge conflicts and bumped black to the last version

**Comment by PsiACE** [comment]
thanks, i will merge it

**Pull request merged**
